### ISSUE TITLE
Error: No such DSL method

### ISSUE THREAD

**Issue by yanickvanbarneveld** [wearefine/wpengine-jenkins-shared-libraries#1]
I am retrieving this error when I run my Pipeline:

`java.lang.NoSuchMethodError: No such DSL method 'wpengine' found among steps [archive, bat, build, catchError, checkout, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, echo, emailext, emailextrecipients, envVarsForTool, error, fileExists, getContext, git, input, isUnix, jiraComment, jiraIssueSelector, jiraSearch, junit, library, libraryResource, load, mail, milestone, node, parallel, powershell, properties, publishHTML, pwd, readFile, readTrusted, resolveScm, retry, script, sh, slackSend, sleep, stage, stash, step, svn, timeout, timestamps, tm, tool, unarchive, unstash, validateDeclarativePipeline, waitUntil, withContext, withCredentials, withDockerContainer, withDockerRegistry, withDockerServer, withEnv, wrap, writeFile, ws] or symbols [all, allOf, always, ant, antFromApache, antOutcome, antTarget, any, anyOf, apiToken, architecture, archiveArtifacts, artifactManager, authorizationMatrix, batchFile, bitbucket, bitbucketPush, booleanParam, branch, buildButton, buildDiscarder, caseInsensitive, caseSensitive, certificate, changelog, changeset, checkoutToSubdirectory, checkstyle, choice, choiceParam, cleanWs, clock, cloud, command, credentials, cron, crumb, defaultView, demand, disableConcurrentBuilds, disableResume, docker, dockerCert, dockerfile, downloadSettings, downstream, dry, dumb, durabilityHint, envVars, environment, expression, file, fileParam, filePath, fingerprint, frameOptions, freeStyle, freeStyleJob, fromScm, fromSource, git, github, githubPush, gradle, headRegexFilter, headWildcardFilter, hyperlink, hyperlinkToModels, inheriting, inheritingGlobal, installSource, jdk, jdkInstaller, jgit, jgitapache, jnlp, jobName, label, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, masterBuild, maven, maven3Mojos, mavenErrors, mavenMojos, mavenWarnings, modernSCM, myView, node, nodeProperties, nonInheriting, nonStoredPasswordParam, none, not, overrideIndexTriggers, paneStatus, parameters, password, pattern, pipeline-model, pipelineTriggers, plainText, plot, plugin, pmd, pollSCM, projectNamingStrategy, proxy, queueItemAuthenticator, quietPeriod, remotingCLI, run, runParam, schedule, scmRetryCount, search, security, shell, skipDefaultCheckout, skipStagesAfterUnstable, slave, sourceRegexFilter, sourceWildcardFilter, sshUserPrivateKey, stackTrace, standard, status, string, stringParam, swapSpace, text, textParam, tmpSpace, toolLocation, unsecured, upstream, usernameColonPassword, usernamePassword, viewsTabBar, weather, withAnt, zfs, zip] or globals [currentBuild, docker, env, params, pipeline, scm]
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:176)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:133)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:120)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:1)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:331)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:243)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:231)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE`

Do you know why this happends?

**Comment by cpitkin** [comment]
@yanickvanbarneveld , thank you for using the library!

So there are two things that need to be checked. 

1. In the screenshot below you can see that the library name is the same name given to the function being called in the Jenkinsfile. If you want to change the name you will need to update the Jenkinsfile and in the job config to reflect this change. 

![screen shot 2018-03-13 at 7 49 20 am](https://user-images.githubusercontent.com/1606945/37342635-308adb7a-2693-11e8-9b91-cd45f2343203.png)

2. With those changes in place check that the job is importing the library under the desired name. Below is a snippet of what you should see at the top of the build logs. If you're importing more than one library this may or may not be mixed in with other imports. You will definitely find this before the run starts or the job fails. 

```
Loading library wpengine@v1.0.1
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/wearefine/wpengine-jenkins-shared-libraries.git # timeout=10
Fetching with tags
Fetching upstream changes from https://github.com/wearefine/wpengine-jenkins-shared-libraries.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials Github - username:password
 > git fetch --tags --progress https://github.com/wearefine/wpengine-jenkins-shared-libraries.git +refs/tags/v1.0.1:refs/tags/v1.0.1
Checking out Revision 5e495476574f4cd5d0242f2ba80237409885b8dc (v1.0.1)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 5e495476574f4cd5d0242f2ba80237409885b8dc
Commit message: "Merge branch 'master' of github.com:wearefine/wpengine-jenkins-shared-libraries"
```

**Comment by yanickvanbarneveld** [comment]
`[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/WordPress
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] echo
13:19:17 ***********************************
[Pipeline] echo
13:19:17 CHECKOUT BRANCH: null
[Pipeline] echo
13:19:17 ***********************************
[Pipeline] stage
[Pipeline] { (Checkout)
[Pipeline] git
13:19:18  > git rev-parse --is-inside-work-tree # timeout=10
13:19:18 Fetching changes from the remote Git repository
13:19:18  > git config remote.origin.url git@bitbucket.org:socialbrothers/sbthema.git # timeout=10
13:19:18 Fetching upstream changes from git@bitbucket.org:socialbrothers/sbthema.git
13:19:18  > git --version # timeout=10
13:19:18 using GIT_SSH to set credentials 
13:19:18  > git fetch --tags --progress git@bitbucket.org:socialbrothers/sbthema.git +refs/heads/*:refs/remotes/origin/*
13:19:19  > git rev-parse refs/remotes/origin/null^{commit} # timeout=10
13:19:19  > git rev-parse refs/remotes/origin/origin/null^{commit} # timeout=10
13:19:19  > git rev-parse origin/null^{commit} # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] emailext
13:19:20 Request made to compress build log
13:19:20 An attempt to send an e-mail to empty list of recipients, ignored.
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE`

It is going a little better now, thanks!!
Still it go bad on some things but it finds the groovy script now.

Formatted: https://pastebin.com/XBctnJjJ

**Comment by cpitkin** [comment]
Can you do me a favor and repost the formatted output? I can't quite tell what is going wrong. I think it says it can't find the repo but it is a little hard to tell.

**Comment by yanickvanbarneveld** [comment]
@cpitkin Woops sorry: https://pastebin.com/XBctnJjJ.

![screen shot 2018-03-13 at 14 30 44](https://user-images.githubusercontent.com/5149838/37344609-212b5988-26cb-11e8-99ad-c394482b25c6.png)

**Comment by cpitkin** [comment]
`Branches to build` should be left blank if you want it to build all branches. I would check that your hook is sending the correct branch information. I would recommend you check out this [plugin](https://plugins.jenkins.io/cloudbees-bitbucket-branch-source). 

If you want more help with CI/CD, in general, I am @cpitkin in the devops chat slack community.

**Comment by yanickvanbarneveld** [comment]
Awesome, I got it working with the recommended plugin! 
Thanks for your help!
